# Generated by Django 4.1.5 on 2023-10-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="postal_code",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
